typography_spectrum: 0.3093
color:
  brandColors:
    - '#71c164'
    - '#197b96'
    - '#00ff00'
    - '#000000'
    - '#0000ff'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.0625
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: My first test!
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Test?
    id: 70605bc1-d40f-4423-8062-a29a0ae03960
    type: content
favicon: null
purpose: []
