name: 'My first test!'
favicon: null
layout_spectrum: 0.365970907965675
typography_spectrum: 0.010940023930743337
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5d2d4'
    - '#ebeaeb'
    - '#272727'
    - '#959495'
    - '#5f5e5f'
  brandStrength: 0.125
  lightness: 0.8866071517113596
  saturation: 0.06257080775685608
  rhythmicContrast: 0.30976024828851223
purpose: []
