name: 'My first test!'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3093
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71c164'
    - '#197b96'
    - '#00ff00'
    - '#000000'
    - '#0000ff'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
